version: '3'
services:
  app:
    image: your-image-name
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/music
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Coldkiller-5
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Coldkiller-5
      - MYSQL_DATABASE=music
    ports:
      - 3307:3307
